### ISSUE TITLE
我使用TypeScript实现了把AML转为Token树的功能

### ISSUE THREAD

**Issue by Kamisato-Ayaka-233** [Drelf2018/go-api-markup-language#3]
这是仓库：https://github.com/Kamisato-Ayaka-233/ApiMarkupLanguage

这是我今天从早上8点到现在写出来的小东西。

**Comment by Drelf2018** [comment]
我晚上看看

**Comment by Drelf2018** [comment]
可以

**Comment by Kamisato-Ayaka-233** [comment]
使用`index.ts`文件中的`ApiMarkupLanguage.tokenize(source)`就把文档的字符串可以转换成Token树。

**Comment by Kamisato-Ayaka-233** [comment]
（e，康不懂Go……项目源代码一眼也没康（））
